/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "ADC1_CH1.h"


int main()
{
	RCC_Init();
	GPIOA_Init();
	ADC1_CH1_Init();
	USART_Init();
	char tx_buffer[20];
while(1){
	// Raw integer data type from ADC
	uint16_t adc_reading = Read_ADC_Data();

	          // Character array (string) data type for UART

	// Convert the integer into a printable string with a newline (\r\n)
	sprintf(tx_buffer, "ADC: %d\r\n",adc_reading);

	USART_Send_data(tx_buffer);

}
return 0;
}
